version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: monthly
    target-branch: main
    assignees:
      - ascopes
    labels:
      - ci
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: monthly
    target-branch: main
    assignees:
      - ascopes
    labels:
      - maven
    groups:
      maven:
        patterns:
          - "*"
        exclude-patterns:
          # Excluded from grouping to generate individual PRs:
          # Error Prone and NullAway versions must be kept in lockstep.
          - "com.google.errorprone:*"
          - "com.uber.nullaway:*"
