on:
  workflow_call: {}

jobs:
  compliance:
    name: Check Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Run checks
        run: >-
          ./mvnw 
          -B 
          -Pdependency-scan
          -T8
          -U
          --no-transfer-progress
          -DskipTests=true
          -Dstyle.color=always
          -Dmaven.main.skip
          -Dmaven.jar.skip
          -Dmaven.resources.skip
          -Dmaven.test.skip
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          verify

      - name: Archive Dependency Scan reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-scan-report
          path: |
            **/target/dependency-check-report.html
          retention-days: 30
