on:
  workflow_call: {}

jobs:
  generate-javadocs:
    name: Generate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          # Must use >= JDK 17 for JavaDocs to generate correctly.
          java-version: 17
          cache: 'maven'

      - name: Generate JavaDocs
        run: >-
          ./mvnw 
          -B 
          -T8
          -U
          -pl java-compiler-testing
          --also-make
          --no-transfer-progress
          -Dmaven.test.skip=true
          -Dcheckstyle.skip=true
          -Dlicense.skip=true
          -Dstyle.color=always
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          clean compile javadoc:jar
