on:
  workflow_call: {}
  workflow_dispatch: {}

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os-name:
          - ubuntu-latest
        java-version:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          # Mockito currently does not support this distribution.
          # - 20-ea
        include:
          - os-name: macos-latest
            java-version: 11
          - os-name: windows-latest
            java-version: 11

    name: Tests - JDK ${{ matrix.java-version }} - ${{ matrix.os-name }}
    runs-on: ${{ matrix.os-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize JDK
        uses: actions/setup-java@v3
        with:
          cache: maven
          check-latest: true
          distribution: zulu
          java-version: ${{ matrix.java-version }}

      - name: Compile and run tests
        run: >-
          ./mvnw 
          -B 
          -T8
          -U
          --no-transfer-progress
          '-Dcheckstyle.skip=true'
          '-Dlicense.skip=true'
          '-Dstyle.color=always'
          '-Dmaven.wagon.httpconnectionManager.ttlSeconds=120'
          clean verify

      - name: Annotate test reports with build environment info
        if: always()
        run: >-
          scripts/prepare-test-outputs-for-merge.sh
          ${{ matrix.java-version }}
          ${{ matrix.os-name }}

      - name: Archive Surefire and Jacoco reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports-java-${{ matrix.java-version }}-${{ matrix.os-name }}
          path: |-
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
            **/target/site/jacoco/jacoco*.xml
          retention-days: 5

  publish-test-reports:
    name: Publish test reports
    runs-on: ubuntu-latest
    if: always()
    needs:
      - run-tests

    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Needed to keep actions working correctly.
          fetch-depth: 2

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: 'artifacts/'

      - name: Publish to codecov
        continue-on-error: true
        if: always()
        run: |-
          curl --fail https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --no-default-keyring --keyring trustedkeys.gpg --import
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM
          curl --fail -Os https://uploader.codecov.io/latest/linux/codecov.SHA256SUM.sig
          gpgv codecov.SHA256SUM.sig codecov.SHA256SUM
          shasum -a 256 -c codecov.SHA256SUM
          chmod -v +x codecov
          ./codecov 

      - name: Publish unit test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        continue-on-error: true
        with:
          json_test_case_results: true
          json_thousands_separator: ","
          junit_files: "artifacts/**/TEST-*.xml"
          report_individual_runs: true
          time_unit: "milliseconds"
