name: Mutation tests
on:
  push:
    branches:
      - 'main'
  workflow_call: {}
  workflow_dispatch: {}
  pull_request: {}

jobs:
  mutation-tests:
    name: Mutation tests
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17
          cache: 'maven'

      - name: Run mutation tests
        shell: bash
        # Do not run on multiple threads, the plugin does not support this properly.
        run: >-
          ./mvnw 
          -B
          -U
          -am
          -pl java-compiler-testing
          --no-transfer-progress
          -P mutation
          -Dstyle.color=always
          -Dcheckstyle.skip=true
          -Dlicense.skip=true
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          test

      - name: Archive Surefire and Jacoco reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: reports-mutation
          if-no-files-found: error
          path: |-
            **/target/pit-reports/pit-reports/**
          retention-days: 5
